# Generated by Django 4.0.4 on 2022-05-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_alter_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(default='Drama', max_length=255),
        ),
    ]
