# Generated by Django 4.0.4 on 2022-05-14 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
