# Generated by Django 4.0.4 on 2022-05-16 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0008_rename_address_booking_caddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingno',
            field=models.IntegerField(default=2132131),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatno', models.CharField(max_length=255)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.seat')),
            ],
        ),
    ]
