# Generated by Django 4.0.4 on 2022-05-16 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0009_booking_bookingno_seat_bookedseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedseat',
            name='cinema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.cinema'),
            preserve_default=False,
        ),
    ]
